server:
  port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/codematata_sessions"
    username: willyngash
    password: admin254
    platform: postgres
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 974739320522-qfvnsmhq94gsk95a374te7uscv0gr3uv.apps.googleusercontent.com
            clientSecret: WK5fU7HfdQ2-f2q-Aq8_hLTX
            scope:
              - profile