spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: process.env.GOOGLE_CLIENT_ID
            clientSecret: process.env.GOOGLE_CLIENT_SECRET
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: process.env.GITHUB_CLIENT_ID
            clientSecret: process.env.GITHUB_CLEINT_SECRET
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user