server:
  port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/codematata_sessions"
    username: willyngash
    password: admin254
    platform: postgres
