spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: { YOUR_CLIENT_ID_HERE }
            clientSecret: { YOUR_CLIENT_SECRET_HERE }
            redirectUrl: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
