spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: $GOOGLE_CLIENT_ID
            clientSecret: $GOOGLE_CLIENT_SECRET
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: $GITHUB_CLIENT_ID
            clientSecret: $GITHUB_CLEINT_SECRET
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user